all: map.bin

clean:
	rm *.bin
	rm *.cmp
map.bin: map.asm map_tiles.cmp map_stiles.cmp map_stilecolors.cmp map_strings.cmp map_strings_en.cmp screen_0_0.cmp screen_0_1.cmp screen_0_2.cmp screen_0_3.cmp screen_0_4.cmp screen_1_0.cmp screen_1_1.cmp screen_1_2.cmp screen_1_3.cmp screen_1_4.cmp screen_2_0.cmp screen_2_1.cmp screen_2_2.cmp screen_2_3.cmp screen_2_4.cmp screen_3_0.cmp screen_3_1.cmp screen_3_2.cmp screen_3_3.cmp screen_3_4.cmp screen_4_0.cmp screen_4_1.cmp screen_4_2.cmp screen_4_3.cmp screen_4_4.cmp screen_5_0.cmp screen_5_1.cmp screen_5_2.cmp screen_5_3.cmp screen_5_4.cmp screen_6_0.cmp screen_6_1.cmp screen_6_2.cmp screen_6_3.cmp screen_6_4.cmp screen_7_0.cmp screen_7_1.cmp screen_7_2.cmp screen_7_3.cmp screen_7_4.cmp screen_8_0.cmp screen_8_1.cmp screen_8_2.cmp screen_8_3.cmp screen_8_4.cmp
	pasmo map.asm map.bin map.sym

map_tiles.cmp: map_tiles.asm
	pasmo map_tiles.asm map_tiles.bin
	apack map_tiles.bin map_tiles.cmp

map_stiles.cmp: map_stiles.asm
	pasmo map_stiles.asm map_stiles.bin
	apack map_stiles.bin map_stiles.cmp

map_stilecolors.cmp: map_stilecolors.asm
	pasmo map_stilecolors.asm map_stilecolors.bin
	apack map_stilecolors.bin map_stilecolors.cmp

map_strings.cmp: map_strings.asm
	pasmo map_strings.asm map_strings.bin
	apack map_strings.bin map_strings.cmp

map_strings_en.cmp: map_strings_en.asm
	pasmo map_strings_en.asm map_strings_en.bin
	apack map_strings_en.bin map_strings_en.cmp

screen_0_0.cmp: screen_0_0.asm
	pasmo screen_0_0.asm screen_0_0.bin
	apack screen_0_0.bin screen_0_0.cmp

screen_0_1.cmp: screen_0_1.asm
	pasmo screen_0_1.asm screen_0_1.bin
	apack screen_0_1.bin screen_0_1.cmp

screen_0_2.cmp: screen_0_2.asm
	pasmo screen_0_2.asm screen_0_2.bin
	apack screen_0_2.bin screen_0_2.cmp

screen_0_3.cmp: screen_0_3.asm
	pasmo screen_0_3.asm screen_0_3.bin
	apack screen_0_3.bin screen_0_3.cmp

screen_0_4.cmp: screen_0_4.asm
	pasmo screen_0_4.asm screen_0_4.bin
	apack screen_0_4.bin screen_0_4.cmp

screen_1_0.cmp: screen_1_0.asm
	pasmo screen_1_0.asm screen_1_0.bin
	apack screen_1_0.bin screen_1_0.cmp

screen_1_1.cmp: screen_1_1.asm
	pasmo screen_1_1.asm screen_1_1.bin
	apack screen_1_1.bin screen_1_1.cmp

screen_1_2.cmp: screen_1_2.asm
	pasmo screen_1_2.asm screen_1_2.bin
	apack screen_1_2.bin screen_1_2.cmp

screen_1_3.cmp: screen_1_3.asm
	pasmo screen_1_3.asm screen_1_3.bin
	apack screen_1_3.bin screen_1_3.cmp

screen_1_4.cmp: screen_1_4.asm
	pasmo screen_1_4.asm screen_1_4.bin
	apack screen_1_4.bin screen_1_4.cmp

screen_2_0.cmp: screen_2_0.asm
	pasmo screen_2_0.asm screen_2_0.bin
	apack screen_2_0.bin screen_2_0.cmp

screen_2_1.cmp: screen_2_1.asm
	pasmo screen_2_1.asm screen_2_1.bin
	apack screen_2_1.bin screen_2_1.cmp

screen_2_2.cmp: screen_2_2.asm
	pasmo screen_2_2.asm screen_2_2.bin
	apack screen_2_2.bin screen_2_2.cmp

screen_2_3.cmp: screen_2_3.asm
	pasmo screen_2_3.asm screen_2_3.bin
	apack screen_2_3.bin screen_2_3.cmp

screen_2_4.cmp: screen_2_4.asm
	pasmo screen_2_4.asm screen_2_4.bin
	apack screen_2_4.bin screen_2_4.cmp

screen_3_0.cmp: screen_3_0.asm
	pasmo screen_3_0.asm screen_3_0.bin
	apack screen_3_0.bin screen_3_0.cmp

screen_3_1.cmp: screen_3_1.asm
	pasmo screen_3_1.asm screen_3_1.bin
	apack screen_3_1.bin screen_3_1.cmp

screen_3_2.cmp: screen_3_2.asm
	pasmo screen_3_2.asm screen_3_2.bin
	apack screen_3_2.bin screen_3_2.cmp

screen_3_3.cmp: screen_3_3.asm
	pasmo screen_3_3.asm screen_3_3.bin
	apack screen_3_3.bin screen_3_3.cmp

screen_3_4.cmp: screen_3_4.asm
	pasmo screen_3_4.asm screen_3_4.bin
	apack screen_3_4.bin screen_3_4.cmp

screen_4_0.cmp: screen_4_0.asm
	pasmo screen_4_0.asm screen_4_0.bin
	apack screen_4_0.bin screen_4_0.cmp

screen_4_1.cmp: screen_4_1.asm
	pasmo screen_4_1.asm screen_4_1.bin
	apack screen_4_1.bin screen_4_1.cmp

screen_4_2.cmp: screen_4_2.asm
	pasmo screen_4_2.asm screen_4_2.bin
	apack screen_4_2.bin screen_4_2.cmp

screen_4_3.cmp: screen_4_3.asm
	pasmo screen_4_3.asm screen_4_3.bin
	apack screen_4_3.bin screen_4_3.cmp

screen_4_4.cmp: screen_4_4.asm
	pasmo screen_4_4.asm screen_4_4.bin
	apack screen_4_4.bin screen_4_4.cmp

screen_5_0.cmp: screen_5_0.asm
	pasmo screen_5_0.asm screen_5_0.bin
	apack screen_5_0.bin screen_5_0.cmp

screen_5_1.cmp: screen_5_1.asm
	pasmo screen_5_1.asm screen_5_1.bin
	apack screen_5_1.bin screen_5_1.cmp

screen_5_2.cmp: screen_5_2.asm
	pasmo screen_5_2.asm screen_5_2.bin
	apack screen_5_2.bin screen_5_2.cmp

screen_5_3.cmp: screen_5_3.asm
	pasmo screen_5_3.asm screen_5_3.bin
	apack screen_5_3.bin screen_5_3.cmp

screen_5_4.cmp: screen_5_4.asm
	pasmo screen_5_4.asm screen_5_4.bin
	apack screen_5_4.bin screen_5_4.cmp

screen_6_0.cmp: screen_6_0.asm
	pasmo screen_6_0.asm screen_6_0.bin
	apack screen_6_0.bin screen_6_0.cmp

screen_6_1.cmp: screen_6_1.asm
	pasmo screen_6_1.asm screen_6_1.bin
	apack screen_6_1.bin screen_6_1.cmp

screen_6_2.cmp: screen_6_2.asm
	pasmo screen_6_2.asm screen_6_2.bin
	apack screen_6_2.bin screen_6_2.cmp

screen_6_3.cmp: screen_6_3.asm
	pasmo screen_6_3.asm screen_6_3.bin
	apack screen_6_3.bin screen_6_3.cmp

screen_6_4.cmp: screen_6_4.asm
	pasmo screen_6_4.asm screen_6_4.bin
	apack screen_6_4.bin screen_6_4.cmp

screen_7_0.cmp: screen_7_0.asm
	pasmo screen_7_0.asm screen_7_0.bin
	apack screen_7_0.bin screen_7_0.cmp

screen_7_1.cmp: screen_7_1.asm
	pasmo screen_7_1.asm screen_7_1.bin
	apack screen_7_1.bin screen_7_1.cmp

screen_7_2.cmp: screen_7_2.asm
	pasmo screen_7_2.asm screen_7_2.bin
	apack screen_7_2.bin screen_7_2.cmp

screen_7_3.cmp: screen_7_3.asm
	pasmo screen_7_3.asm screen_7_3.bin
	apack screen_7_3.bin screen_7_3.cmp

screen_7_4.cmp: screen_7_4.asm
	pasmo screen_7_4.asm screen_7_4.bin
	apack screen_7_4.bin screen_7_4.cmp

screen_8_0.cmp: screen_8_0.asm
	pasmo screen_8_0.asm screen_8_0.bin
	apack screen_8_0.bin screen_8_0.cmp

screen_8_1.cmp: screen_8_1.asm
	pasmo screen_8_1.asm screen_8_1.bin
	apack screen_8_1.bin screen_8_1.cmp

screen_8_2.cmp: screen_8_2.asm
	pasmo screen_8_2.asm screen_8_2.bin
	apack screen_8_2.bin screen_8_2.cmp

screen_8_3.cmp: screen_8_3.asm
	pasmo screen_8_3.asm screen_8_3.bin
	apack screen_8_3.bin screen_8_3.cmp

screen_8_4.cmp: screen_8_4.asm
	pasmo screen_8_4.asm screen_8_4.bin
	apack screen_8_4.bin screen_8_4.cmp

