; Sprite offsets, used by the animation engine

SPRITE_OFFSET_IDLE:			EQU	 SPRITE_START_ADDR
SPRITE_OFFSET_TURN:			EQU	 SPRITE_START_ADDR+1*384
SPRITE_OFFSET_WALK:			EQU	 SPRITE_START_ADDR+2*384
SPRITE_OFFSET_FALL:			EQU	 SPRITE_START_ADDR+8*384
SPRITE_OFFSET_CROUCH:		EQU	 SPRITE_START_ADDR+10*384
SPRITE_OFFSET_UNSHEATHE:	EQU	 SPRITE_START_ADDR+13*384
SPRITE_OFFSET_IDLE_SWORD:	EQU	 SPRITE_START_ADDR+14*384
SPRITE_OFFSET_WALK_SWORD:	EQU	 SPRITE_START_ADDR+15*384
SPRITE_OFFSET_HIGH_SWORD:	EQU	 SPRITE_START_ADDR+18*384
SPRITE_OFFSET_FORW_SWORD:	EQU	 SPRITE_START_ADDR+22*384
SPRITE_OFFSET_COMBO1_SWORD:	EQU	 SPRITE_START_ADDR+26*384
SPRITE_OFFSET_LOW_SWORD:	EQU	 SPRITE_START_ADDR+28*384
SPRITE_OFFSET_BACK_SWORD:	EQU	 SPRITE_START_ADDR+32*384
SPRITE_OFFSET_BLOCK_SWORD:	EQU	 SPRITE_OFFSET_LOW_SWORD+1152
SPRITE_OFFSET_OUCH_SWORD:	EQU	 SPRITE_START_ADDR+36*384
SPRITE_OFFSET_DIE:		    EQU	 SPRITE_START_ADDR+37*384

; Be careful! The following offsets *may* change if more common animations are added

SPRITE_OFFSET_OUCH:		    EQU	 SPRITE_START_ADDR			;	41*384
SPRITE_OFFSET_JUMP_UP:		EQU	 SPRITE_START_ADDR+1*384	;	42*384
SPRITE_OFFSET_SHORTJUMP:	EQU	 SPRITE_START_ADDR+9*384	;	50*384
SPRITE_OFFSET_LONGJUMP:		EQU	 SPRITE_START_ADDR+14*384	;	55*384
SPRITE_OFFSET_RUN:		    EQU	 SPRITE_START_ADDR+19*384	;	60*384
SPRITE_OFFSET_BRAKE:		EQU	 SPRITE_START_ADDR+23*384	;	64*384
SPRITE_OFFSET_BRAKETURN:	EQU	 SPRITE_START_ADDR+24*384	;	65*384
SPRITE_OFFSET_SWITCH:		EQU	 SPRITE_START_ADDR+26*384	;	67*384
SPRITE_OFFSET_GRAB:		    EQU	 SPRITE_START_ADDR+28*384	;	69*384

